openapi: 3.0.0
info:
  title: User Profile API
  version: 1.0.0
  description: API for managing user profiles (preferences).

paths:
  /profile:
    get:
      summary: Get user profile
      description: Retrieves the profile (preferences) for the currently authenticated user.
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Profile'
        '401':
          description: Unauthorized
    put:
      summary: Update user profile
      description: Updates the profile (preferences) for the currently authenticated user.
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Profile'
      responses:
        '200':
          description: Profile updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Profile'
        '400':
          description: Invalid request body
        '401':
          description: Unauthorized

components:
  schemas:
    Profile:
      type: object
      properties:
        experienceLevel:
          type: string
          enum: [Novice, Professional]
        language:
          type: string
          enum: [English, Urdu]
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
